Layout/EmptyLines:
  Enabled: false
Layout/LeadingEmptyLines:
  Enabled: false


Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/SymbolArray:
  Enabled: false
